python-pyflame: Disable for mips arch
Fails to build as support is missing

src/ptrace.cc:135:48: error: 'regs' has incomplete type

(From meta-openembedded commit: 38717e1f552575d7726c47cbcd88f51ea521d4b7)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Tim Orling <ticotimo@gmail.com>