python-socketio: prevent python2 socketio depending on python3-aiohttp
* enable client and asyncio_client PACKAGECONFIGs only in python3-socketio, because
  there is no python-websockets, python--websocket-client recipes for python2 version
* fixes:
  ERROR: Nothing RPROVIDES 'python3-aiohttp' (but
    meta-oe/meta-python/recipes-devtools/python/python-socketio_4.3.1.bb
    RDEPENDS on or otherwise requires it)
  when python3-aiohttp is blacklisted

(From meta-openembedded commit: 26656c1cd1767c7d6de1d6380ebb92498cf8e912)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Tim Orling <ticotimo@gmail.com>