python-attrs: fix typo in depends
ERROR: Nothing RPROVIDES 'python-crypto' (but ../meta-python/recipes-devtools/python/python-attrs_17.4.0.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python-crypto' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-crypto']

(From meta-openembedded commit: dfccaebd48160b7e7b5a50f65fe5aad298bf9ca3)

Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Tim Orling <ticotimo@gmail.com>