python-twisted: Fix dependencies of twisted modules
When installing just "twisted-web" on a device, none of the dependencies
are being copied, it wouldn't even install python-core. Fix the recipe so
that its packages have proper dependencies, and no longer require to install
the empty python-twisted meta recipe.

Add "python-contextlib" to the core dependencies and stop causing systems
to crash with:
  File "/usr/lib/python2.7/site-packages/twisted/python/threadpool.py", line 18, in <module>
    ImportError: No module named contextlib

(From meta-openembedded commit: 10a483537723255549ec9030d619e0e3f60772ac)

Signed-off-by: Mike Looijmans <milo-software@users.sourceforge.net>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Tim Orling <ticotimo@gmail.com>