python-setuptools: simplify RDEPENDS setting
* python2 version from meta-python2 caused parsing error now, which unfortunately left bitbake stuck after:
  ERROR: meta-python2/recipes-devtools/python/python-setuptools_42.0.2.bb: QA Issue: meta-python2/recipes-devtools/python/python-setuptools_42.0.2.bb: Variable RPROVIDES is set as not being package specific, please fix this. [pkgvarcheck]
  ERROR: meta-python2/recipes-devtools/python/python-setuptools_42.0.2.bb: Fatal QA errors found, failing task.
  ERROR: Failed to parse recipe: meta-python2/recipes-devtools/python/python-setuptools_42.0.2.bb

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>