python-lxml: do not overwrite inherited DEPENDS
python-lxml recipe inherits setuptools3 and after that includes
python-lxml.inc. In the current situation DEPENDS inherited by
setuptools3-tree are overwritten causing:

DEBUG: Executing shell function do_compile
/home/superandy/tmp/oe-core-glibc/work/x86_64-linux/python3-lxml-native/3.4.4-r0/temp/run.do_compile.30454: line 118: /home/superandy/tmp/oe-core-glibc/sysroots/x86_64-linux/usr/bin/python3-native/python3: No such file or directory
ERROR: python3 setup.py build_ext execution failed.
WARNING: /home/superandy/tmp/oe-core-glibc/work/x86_64-linux/python3-lxml-native/3.4.4-r0/temp/run.do_compile.30454:1 exit 1 from
  exit 1
ERROR: Function failed: do_compile (log file is located at /home/superandy/tmp/oe-core-glibc/work/x86_64-linux/python3-lxml-native/3.4.4-r0/temp/log.do_compile.30454)

(From meta-openembedded commit: db539ce16e7d34bf2c71675d1417b7f7172e7e03)

Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Tim Orling <ticotimo@gmail.com>