python-prettytable: fix files permissions
Got this runtime error:

IOError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/prettytable-0.7.2-py2.7.egg-info/PKG-INFO'

After some investigation, it looks like the pypi package is the culprit
as almost all the files in the tar.gz are set to 600 instead of 644.

(From meta-openembedded commit: 1e322de8e68a50a14bb1d4be83912e1a437daf3a)

Signed-off-by: Marc Ferland <ferlandm@amotus.ca>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Tim Orling <ticotimo@gmail.com>